services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    container_name: catalog-api
    depends_on:
      - mongo-db
      - redis-db
    ports:
      - 8089:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DocumentDb__ConnectionString=mongodb://root:root@mongo-db:27017/?authSource=admin
      - CacheDb__ConnectionString=redis-db:6379
    networks:
      - catalog-network
  
  mongo-db:
    image: mongo:8
    restart: unless-stopped
    container_name: mongodb-db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 27017:27017
    volumes:
      - catalog_data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=CatalogDatabase
    networks:
      - catalog-network

  redis-db:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: redis-db
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=yourStrong(!)Password
      - REDIS_PORT=6379
    networks:
      - catalog-network

  insight:
    image: redis/redisinsight
    restart: unless-stopped
    container_name: redis-insight
    depends_on:
      - redis-db
    ports:
      - 8085:5540
    environment:
      - RI_REDIS_HOST=redis-db
      - RI_REDIS_PORT=6379
    networks:
      - catalog-network
        
volumes:
  catalog_data:
    
networks:
  catalog-network:
    driver: bridge
